baseURL = "http://example.org/"
languageCode = "en-us"
title = "Guido Sangiovanni"
theme = "jeffprod"
[permalinks]
    post = "/:year/:filename"

[taxonomies]
    tag = "tags"
    archive = "archives"
